# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "gate" do |gate|
    gate.vm.box = "generic/debian10"
    gate.vm.network "public_network", bridge: "enp3s0",ip: "192.168.0.200" #IP from home router range
    gate.vm.network "private_network", ip: "10.10.0.2", auto_config: false
    gate.vm.network "private_network", ip: "172.16.0.2", auto_config: false

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end


  config.vm.define "node1" do |node1|
    node1.vm.box = "generic/debian10"
    node1.vm.network "private_network", ip: "10.10.0.10", auto_config: false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "generic/debian10"
    node2.vm.network "private_network", ip: "172.16.0.10", auto_config: false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end 
end
